# Generated by Django 2.2.4 on 2022-10-06 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registration_app', '0003_auto_20221006_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('date_planted', models.DateField(default=datetime.date(2022, 10, 6))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='login_registration_app.User')),
                ('visited_by', models.ManyToManyField(related_name='visited_trees', to='login_registration_app.User')),
            ],
        ),
    ]
