# Generated by Django 2.2.4 on 2022-10-06 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arbortrary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='date_planted',
            field=models.DateField(default=datetime.datetime(2022, 10, 6, 7, 45, 43, 382754, tzinfo=utc)),
        ),
    ]
