# Generated by Django 2.2.4 on 2022-10-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbortrary_app', '0003_auto_20221006_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='num_of_visits',
            field=models.IntegerField(default=0),
        ),
    ]
